export enum ActionType {
    LOAD_ROLES = 'LOAD ROLES',
    LOAD_ROLE_SUCCESS = 'LOAD ROLE SUCCESS',
    LOAD_ROLE_FAILURE = 'LOAD ROLE FAILURE',
    LOAD_PROFILES = 'LOAD PROFILES',
    LOAD_PROFILE_SUCCESS = 'LOAD PROFILE SUCCESS',
    LOAD_PROFILE_FAILURE = 'LOAD PROFILE FAILURE',
}
