name: creditcard

on:
    push:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: '17'
            - run: npm install -g yarn
            - run: yarn install --frozen-lockfile
            - run: yarn format
            - run: yarn lint
            - run: yarn build
